# Generated by Django 5.0.4 on 2024-04-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='cty',
            new_name='city',
        ),
    ]
